# Generated by Django 5.2.3 on 2025-06-14 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('username', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('Phone', models.CharField(max_length=15, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_email', models.EmailField(max_length=254)),
                ('lead_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agent')),
            ],
        ),
    ]
